/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppPrivateRouteImport } from './routes/_app/_private'
import { Route as AppPrivateNotesRouteImport } from './routes/_app/_private/notes'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/_auth/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPrivateRoute = AppPrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivateNotesRoute = AppPrivateNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppPrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/test': typeof TestRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/notes': typeof AppPrivateNotesRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/': typeof AppIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/notes': typeof AppPrivateNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/test': typeof TestRoute
  '/_app/_private': typeof AppPrivateRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_private/notes': typeof AppPrivateNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test' | '/signin' | '/signup' | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/test' | '/' | '/signin' | '/signup' | '/notes'
  id:
    | '__root__'
    | '/_app'
    | '/test'
    | '/_app/_private'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/_private/notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  TestRoute: typeof TestRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_private': {
      id: '/_app/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPrivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_private/notes': {
      id: '/_app/_private/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppPrivateNotesRouteImport
      parentRoute: typeof AppPrivateRoute
    }
  }
}

interface AppPrivateRouteChildren {
  AppPrivateNotesRoute: typeof AppPrivateNotesRoute
}

const AppPrivateRouteChildren: AppPrivateRouteChildren = {
  AppPrivateNotesRoute: AppPrivateNotesRoute,
}

const AppPrivateRouteWithChildren = AppPrivateRoute._addFileChildren(
  AppPrivateRouteChildren,
)

interface AppRouteChildren {
  AppPrivateRoute: typeof AppPrivateRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPrivateRoute: AppPrivateRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  TestRoute: TestRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
